deleteBranchAfterMerge: true
mergeMethod: squash
reportStatus: true
updateBranch: true

minApprovals:
  COLLABORATOR: 0
  OWNER: 0

requiredReviewers:
  - nikkeyl

requiredLabels:
  - dependencies

mergeCommitMessage: |
  {title} (#{number})

  {body}
