deleteBranchAfterMerge: true
mergeMethod: squash
reportStatus: true
updateBranch: true

minApprovals:
  COLLABORATOR: 0
  OWNER: 0

mergeCommitMessage: |
  {title} (#{number})

  {body}

requiredLabels:
  - dependencies
