name: Bug Report
description: Create a report to help us improve this project!
title: 'bug: '
labels:
  - bug
assignees:
  - nikkeyl

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Describe what happened.
      placeholder: Tell us what you see
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Please Reproduce the Bug Step By Step
      description: Please provide as much step-by-step detail as possible.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen when the reproduce steps?
      placeholder: Tell us what you expected to see
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Add Screenshots
      description: Can you provide screenshots?
      placeholder: Your screenshots

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste log output. No need for backticks.
      placeholder: Log
      render: bash

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
