name: Docs Enhancement
description: Create a report to help us improve this project!
title: 'documentation: '
labels:
  - documentation
assignees:
  - nikkeyl

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this docs enhancement!

  - type: textarea
    id: describe
    attributes:
      label: Describe
      description: Describe your enhancements!
      placeholder: Awesome enhancement
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I Agree to Follow This Project's Code of Conduct
          required: true
