name: Enhancement Request
description: Create a report to help us improve this project!
title: 'enhancement: '
labels:
  - enhancement
assignees:
  - nikkeyl

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this enhancement request!

  - type: textarea
    id: describe
    attributes:
      label: Describe
      description: Describe your enhancement!
      placeholder: Provide a step-by-step description of the suggested enhancement
    validations:
      required: true

  - type: textarea
    id: explain
    attributes:
      label: Explain
      description: Explain why this enhancement would be useful.
      placeholder: How your enhancement could be useful
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I Agree to Follow This Project's Code of Conduct
          required: true
