name: Refactor Request
description: Create a report to help us improve this project!
title: 'refactor: '
labels:
  - refactor
assignees:
  - nikkeyl

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this refactor request!

  - type: textarea
    id: refactor
    attributes:
      label: Refactor
      description: What needs refactor?
      placeholder: Tell us where you found the unfinished code
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
