name: Wiki Improvement
description: Create a report to help us improve this project!
title: 'documentation: '
labels:
  - documentation
assignees:
  - nikkeyl

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this wiki request!

  - type: textarea
    id: documentation-improve
    attributes:
      label: Documentation Improvements
      description: Describe your improvements!
      placeholder: Awesome improvement
    validations:
      required: true

  - type: textarea
    id: add-documentation
    attributes:
      label: Add New Documentation
      description: What documentation did you want to add?
      placeholder: Document name and description

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
