name: Auto Merge Dependabot Pull Request

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-dependabot-pull-request:
    name: Auto Merge Dependabot Pull Request

    if: ${{ github.actor == 'dependabot[bot]' }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Merge
        run: gh pr merge $PR_URL --auto --squash
