name: Commit Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  commit-lint:
    name: Lint

    runs-on: ubuntu-latest
    timeout-minutes: 10

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint
        uses: wagoid/commitlint-github-action@v5
