name: Dependabot Auto Merge Pull Request

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge-pull-request:
    name: Merge

    runs-on: ubuntu-latest
    timeout-minutes: 10

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --merge '$PULL_REQUEST_URL'
