name: Editorconfig

on:
  workflow_run:
    workflows:
      - CodeQL
    types:
      - completed
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  editorconfig:
    name: Editorconfig

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set Up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint:editorconfig
