name: ESLint

on:
  workflow_run:
    workflows:
      - CodeQL
    types:
      - completed
  pull_request:
    branches:
      - main
    paths:
      - 'core/*.ts'
      - 'specs/**/*.spec.ts'
  push:
    branches:
      - main
    paths:
      - 'core/*.ts'
      - 'specs/**/*.spec.ts'

jobs:
  eslint:
    name: Lint

    runs-on: ubuntu-latest
    timeout-minutes: 10

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          cache: npm
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:ts
