name: Release

on:
  workflow_run:
    workflows:
      - ESLint
    types:
      - completed
  push:
    branches:
      - main

jobs:
  release:
    name: Release

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RELEASE_UNBLOCKER_APP_ID }}
          private_key: ${{ secrets.RELEASE_UNBLOCKER_APP_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set Up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set Up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install Dependencies
        run: pnpm i

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: pnpm release
