name: Stale

on:
  schedule:
    - cron: 0 0 * * *

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Stale
        uses: actions/stale@v9
        with:
          exempt-issue-labels: bug,fix,security,question
          exempt-pr-labels: bug,fix,security
          stale-issue-label: stale
          stale-pr-label: stale
          close-issue-label: close
          close-pr-label: close
          stale-issue-message: This issue is stale. You can reopen it again.
          stale-pr-message: This Pull Request is stale. You can reopen it again.
          close-issue-message: This issue is closed.
          close-pr-message: This Pull Request is closed.
